export const CHOOSE_YEAR = 'CHOOSE_YEAR'
export const CHOOSE_DAYS_IN_MONTH_CHOSEN_YEAR =
  'CHOOSE_DAYS_IN_MONTH_CHOSEN_YEAR'
export const CHOOSE_BETWEEN_DAY_TO_DAY = 'CHOOSE_BETWEEN_DAY_TO_DAY'
export const CHOOSE_BETWEEN_YEARS = 'CHOOSE_BETWEEN_YEARS'
export const SHOW_FULL_MONTH = 'SHOW_FULL_MONTH'
export const SET_KINERET = 'SET_KINERET'
export const SET_PIE = 'SET_PIE'
